spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: api
      return-body-on-create: true
      return-body-on-update: true
  mail:
    host:
    username:
    password:
    protocol: smtp